### ISSUE TITLE
[Flink AI Flow] Events send order is not same as task completion order

### ISSUE THREAD

**Issue by jiangxin369** [flink-extended/dl-on-flink#130]
Consider the following scenario:
the DAG looks like [op1, op2 -> op3], with event-based scheduler，op1 completed before op2, but the TaskStatusChanged event of op2 is sent to scheduler before op1.

when EventBasedScheduler#_find_schedulable_tasks receives a TaskStatusChanged event, it will check the task status of op1 and op2. So it would find op1 and op2 are SUCCEESS at each time it receives TaskStatusChanged event, and op3 would be triggered twice.

**Comment by Sxnan** [comment]
AIFlow has been moved to https://github.com/flink-extended/ai-flow.

**Comment by Sxnan** [comment]
AIFlow has been moved to https://github.com/flink-extended/ai-flow.

Please reopen the issue there if necessary.
