### ISSUE TITLE
[NotificationService] NS support consuming message since earliest or latest version

### ISSUE THREAD

**Issue by jiangxin369** [flink-extended/dl-on-flink#238]
### Describe the feature

NS should support consuming message since earliest or latest version like kafka, latest by default.

### Describe the solution you'd like

Client could pass version as earliest or latest when start_listen_event, Notification Master handles the race condition and return messages since specific version.

**Comment by Sxnan** [comment]
AIFlow has been moved to https://github.com/flink-extended/ai-flow.

Please reopen the issue there if necessary.
