### ISSUE TITLE
[Flink-AI-Flow] [Documents] Improve Enum constants display

### ISSUE THREAD

**Issue by bgeng777** [flink-extended/dl-on-flink#368]
### Describe the feature

From:
![image](https://user-images.githubusercontent.com/80749729/125908527-6af91bfb-e900-4ab0-8ae4-19b2c4ecae67.png)
To:
![image](https://user-images.githubusercontent.com/80749729/125908609-7cbd027e-64af-4d3b-bed8-e75989c25b78.png)

**Comment by Sxnan** [comment]
AIFlow has been moved to https://github.com/flink-extended/ai-flow.

Please reopen the issue there if necessary.
