### ISSUE TITLE
找不到proto包

### ISSUE THREAD

**Issue by keda969** [flink-extended/dl-on-flink#55]
执行代码报找不到程序包：com.alibaba.flink.ml.proto不存在

import com.alibaba.flink.ml.proto.ContextResponse;
import com.alibaba.flink.ml.proto.ContextRequest;
import com.alibaba.flink.ml.proto.ContextResponse;
import com.alibaba.flink.ml.proto.NodeServiceGrpc;

我看到有这个包，也有相关.proto文件，需要怎么操作解决这个问题？

**Comment by tywtyw** [comment]
proto文件对应生成的类会生成在对应模块的target目录下的generated-sources目录下，ide中可将这个文件标记为source root
