### ISSUE TITLE
[Flink AI Flow] Kindly provide an example about real time feature engineering of window and global features

### ISSUE THREAD

**Issue by LongxingTan** [flink-extended/dl-on-flink#591]
### Describe the feature

Would you kindly provide an example of real time feature engineering? especially about window or global features. For transform feature engineering, I can see that how ```af.transform``` works. But if it comes to some complex feature engineerings, like groupby in pandas, or target encoding, that's also widely used. If an example is provided, that's will be nice. Thanks

**Comment by SteNicholas** [comment]
@LongxingTan , the example of the real time feature engineering makes sense. It's recommended to use Flink SQL to handle the feature engineering transformation based on PyFlink Table in `FlinkPythonProcessor`. What's more, we would conside to provide users with the example above mentioned. BTW, do you have interest to contribute the example?

**Comment by LongxingTan** [comment]
@SteNicholas 
Sounds good. Even I'm not so familiar with Flink, I will try it. Any suggestion about which existing example I could work to add more features, or I start a new example with the current dataset ?

**Comment by SteNicholas** [comment]
@LongxingTan , you could refer to the wide&deep example to start your example contribution.
