### ISSUE TITLE
jar包下载不下来

### ISSUE THREAD

**Issue by JaneFy** [flink-extended/dl-on-flink#701]
### Describe the bug
maven打包jar包的过程卡住，jar包下载不下来
Downloading from alimaven: http://maven.aliyun.com/nexus/content/groups/public/org/tensorflow/libtensorflow_jni/1.15.0/libtensorflow_jni-1.15.0.jar

#### Operating system
Ubuntu 20.04

**Comment by Sxnan** [comment]
看起来像是网络的问题。直接 wget http://maven.aliyun.com/nexus/content/groups/public/org/tensorflow/libtensorflow_jni/1.15.0/libtensorflow_jni-1.15.0.jar 能够下载下来吗？

**Comment by JaneFy** [comment]
> 

wget可以下载

**Comment by JaneFy** [comment]
> wget可以下载

**Comment by JaneFy** [comment]
> 看起来像是网络的问题。直接 wget http://maven.aliyun.com/nexus/content/groups/public/org/tensorflow/libtensorflow_jni/1.15.0/libtensorflow_jni-1.15.0.jar 能够下载下来吗？
wget可以下载

**Comment by JaneFy** [comment]
> 看起来像是网络的问题。直接 wget http://maven.aliyun.com/nexus/content/groups/public/org/tensorflow/libtensorflow_jni/1.15.0/libtensorflow_jni-1.15.0.jar 能够下载下来吗？

wget可以下载@[Sxnan](https://github.com/Sxnan)

**Comment by Sxnan** [comment]
可以麻烦贴一下 maven 的完整日志吗？

**Comment by JaneFy** [comment]
> 可以麻烦贴一下 maven 的完整日志吗？

![image](https://user-images.githubusercontent.com/21964480/154063741-c113fad7-4d09-49cc-8c0a-17dd40160d2d.png)
@[Sxnan](https://github.com/Sxnan)

**Comment by Sxnan** [comment]
> > 可以麻烦贴一下 maven 的完整日志吗？
> 
> ![image](https://user-images.githubusercontent.com/21964480/154063741-c113fad7-4d09-49cc-8c0a-17dd40160d2d.png) @[Sxnan](https://github.com/Sxnan)

我这边好像没法复现。你用的 mvn 命令是什么呢？能把完整的 maven 日志导到一个文本传上来看看吗？
