### ISSUE TITLE
looks like property key REMOTE_CODE_ZIP_FILE("remote_code_zip_file") has no effect when training without input

### ISSUE THREAD

**Issue by 1202zhyl** [flink-extended/dl-on-flink#744]
### Describe the bug
Master Branch.

I am running a training task, which input data is directly read by tensorflow itself, so the flink task submitted has no input. 
Then I go deep into the source code, I found that ENV VAR USE_DISTRIBUTE_CACHE will be set in this situation, thus when NodeServer calls the function prepareRuntimeEnv(), then REMOTE_CODE_ZIP_FILE will have no effect at all.

I think zip file should be necessarily support, a large code project contains lots of code and configuration files.
### Additional context
Please correct me if I made a mistake, right now the only thing I can do if I want to use the zip file is to modify the source code and compile it.

**Comment by Sxnan** [comment]
Sorry for the late reply. 

Using the Java API, you should package your code into a python virtual environment zip and use the `ClusterConfig.Builder#setPythonVirtualEnvZip` to set the virtual environment. The file in the site-package folder will be added to the `PYTHONPATH`. 

With Python API, it is not integrated with the PyFlink dependencies management, you can refer to [here](https://nightlies.apache.org/flink/flink-docs-release-1.14/docs/dev/python/dependency_management/) for instructions.

**Comment by 1202zhyl** [comment]
> Sorry for the late reply.
> 
> Using the Java API, you should package your code into a python virtual environment zip and use the `ClusterConfig.Builder#setPythonVirtualEnvZip` to set the virtual environment. The file in the site-package folder will be added to the `PYTHONPATH`.
> 
> With Python API, it is not integrated with the PyFlink dependencies management, you can refer to [here](https://nightlies.apache.org/flink/flink-docs-release-1.14/docs/dev/python/dependency_management/) for instructions.

Thanks, I'll give it a try. closed.
