### ISSUE TITLE
group id is too big - Error when building Java files from source.

### ISSUE THREAD

**Issue by maurodlt** [flink-extended/dl-on-flink#760]
Hello, I was trying to install dl-on-flink using the following command `python3 -m pip install --upgrade dl-on-flink-framework`  but I was getting an error. Thus , I decided to build it from source, which is generating the error mentioned below. 

### Describe the bug

Error when building Java files from source.

### Your environment

MacOS 12.4
flink-1.14.4
TensorFlow 2.5
Java 8
Python 3.8

### To Reproduce
Steps to reproduce the behavior (if you can):
`git clone https://github.com/flink-extended/dl-on-flink.git`
`cd dl-on-flink`
`git submodule update --init --recursive`
`mvn -DskipTests clean install`

### Error log

> [INFO] Reading assembly descriptor: src/assembly/dist.xml
[INFO] Copying files to /Users/mauro.dalleluccatosi/Documents/Flink/dl-on-flink/dl-on-flink-dist/target/dl-on-flink-dist-0.6.0-SNAPSHOT-bin
[WARNING] Assembly file: /Users/mauro.dalleluccatosi/Documents/Flink/dl-on-flink/dl-on-flink-dist/target/dl-on-flink-dist-0.6.0-SNAPSHOT-bin is not a regular file (it may be a directory). It cannot be attached to the project build for installation or deployment.
[INFO] Building tar: /Users/mauro.dalleluccatosi/Documents/Flink/dl-on-flink/dl-on-flink-dist/target/dl-on-flink-dist-0.6.0-SNAPSHOT-bin.tgz
[WARNING] Entry: dl-on-flink-dist-0.6.0-SNAPSHOT/lib/dl-on-flink-tensorflow-2.x-0.6.0-SNAPSHOT-jar-with-dependencies.jar longer than 100 characters.
[WARNING] Resulting tar file can only be processed successfully by GNU compatible tar commands
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for dl-on-flink 0.6.0-SNAPSHOT:
[INFO] 
[INFO] dl-on-flink ........................................ SUCCESS [  5.645 s]
[INFO] dl-on-flink-framework .............................. SUCCESS [01:09 min]
[INFO] dl-on-flink-operator ............................... SUCCESS [ 25.692 s]
[INFO] dl-on-flink-tensorflow-common ...................... SUCCESS [  5.343 s]
[INFO] dl-on-flink-tensorflow ............................. SUCCESS [04:19 min]
[INFO] dl-on-flink-tensorflow-2.x ......................... SUCCESS [02:15 min]
[INFO] dl-on-flink-pytorch ................................ SUCCESS [ 31.789 s]
[INFO] dl-on-flink-examples ............................... SUCCESS [  0.188 s]
[INFO] dl-on-flink-examples-tensorflow .................... SUCCESS [ 21.254 s]
[INFO] dl-on-flink-examples-pytorch ....................... SUCCESS [ 20.828 s]
[INFO] dl-on-flink-examples-tensorflow-2.x ................ SUCCESS [ 18.612 s]
[INFO] dl-on-flink-lib .................................... SUCCESS [  7.863 s]
[INFO] dl-on-flink-dist ................................... FAILURE [  2.553 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10:05 min
[INFO] Finished at: 2022-07-20T16:57:01+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.3.0:single (bin) on project dl-on-flink-dist: Execution bin of goal org.apache.maven.plugins:maven-assembly-plugin:3.3.0:single failed: group id '1429829944' is too big ( > 2097151 ). Use STAR or POSIX extensions to overcome this limit -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :dl-on-flink-dist

Thanks for the assistance!

**Comment by Sxnan** [comment]
Hi @maurodlt! 

I think the problem is that the GroupId of your mac user is too big, 1429829944' is too big ( > 2097151 ), bigger than expected. You can see more detailed explanation [here.](https://stackoverflow.com/a/46698905) The solution seems to add `<tarLongFileMode>posix<tarLongFileMode>` to the maven-assembly-plugin configuration. 

You can add the configuration at `dl-on-flink-dist/pom.xml`, so that the maven-assembly-plugin configuration becomes the following:
```
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>3.3.0</version>
                <executions>
                    <execution>
                        <id>bin</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <configuration>
                            <descriptors>
                                <descriptor>src/assembly/dist.xml</descriptor>
                            </descriptors>
                            <tarLongFileMode>posix</tarLongFileMode>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

Could you post the error when you use the command `python3 -m pip install --upgrade dl-on-flink-framework`? I think it is valuable and I cannot produce the error in my environment.

**Comment by maurodlt** [comment]
Hello @Sxnan,

thank you for your reply. I could successfully install dl-on-flink!

The error when using the command `python3 -m pip install --upgrade dl-on-flink-framework` was due to an older pip version. After updating pip to version 22.2 I could run the command without further errors.

Thanks again!
